# Installation: https://github.com/causefx/Organizr/

version: '3.9'
services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=${ORGANIZR_PUID}
      - PGID=${ORGANIZR_PGID}
    volumes:
      - /opt/appdata/organizrv2:/config
    ports:
      - 9284:80
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
