version: '3.9'
services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    hostname: organizr
    environment:
      - PUID=${ORGANIZR_PUID}
      - PGID=${ORGANIZR_PGID}
      - TZ=${ORGANIZR_TZ}
    volumes:
      - /opt/appdata/organizrv2:/config
    ports:
      - 9284:80
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
