version: '3.9'
services:
  appflowy_client:
    image: appflowyio/appflowy_client:0.3.5
    container_name: appflowy_client
    hostname: appflowy_client
    environment:
      - DISPLAY=${APPFLOWY_CLIENT_DISPLAY}
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /mnt/appdata/appflowy_client:/home/appflowy
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
