# Installation: https://docs.appflowy.io/docs/appflowy/install-appflowy/installation-methods/installing-with-docker

version: '3.9'
services:
  appflowy_client:
    image: appflowyio/appflowy_client:0.6.2
    container_name: appflowy_client
    environment:
      - DISPLAY=${APPFLOWY_CLIENT_DISPLAY}
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /opt/appdata/appflowy_client:/home/appflowy
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
