version: '3.9'
services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:2.10.7
    ports:
      - 8001:80
      - 44301:443
      - 8181:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/traefik/
    environment:
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN}
      - CLOUDFLARE_EMAIL=${TRAEFIK_CLOUDFLARE_EMAIL}
      - DOMAIN=${TRAEFIK_DOMAIN}
      - DOCKER_NETWORK=${DOCKER_NETWORK}
    restart: unless-stopped
    depends_on:
      - dockersocket
    networks:
      - proxy

  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    environment:
      - CONTAINERS=${DOCKERSOCKET_CONTAINERS}
      - POST=${DOCKERSOCKET_POST}
    privileged: true
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
