version: '3.9'
services:
  coder:
    image: codercom/coder:1.44.3
    container_name: coderd
    hostname: coderd
    ports:
      - 7076:7080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/coder/.coder:/var/run/coder

    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
