name: 🔄 Pull Request
description: Propose a pull request for this project
title: '[PR] <title>'
labels: [enhancement]
assignees: [NorkzYT]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a pull request!
  - type: checkboxes
    attributes:
      label: Have you pulled the latest changes from the main branch?
      description: Please make sure you have the latest changes before submitting.
      options:
        - label: I have pulled the latest changes
          required: true
  - type: textarea
    id: what-changed
    attributes:
      label: What changes does this pull request make?
      description: |
        A clear and concise description of what the changes are. Ex. This adds a new feature that allows [...]
      placeholder: Describe the changes made.
    validations:
      required: true
  - type: textarea
    id: implementation-details
    attributes:
      label: Describe the implementation details
      description: A clear and concise description of the implementation and any technical choices made during development.
    validations:
      required: true
  - type: textarea
    id: alternative-implementation
    attributes:
      label: Were any alternative implementations considered?
      description: A clear and concise description of any alternative implementations or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else we should know?
      description: |
        Links? References? Testing considerations?

        Add any other context, screenshots, or code snippets about the pull request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please review the following checklist before submitting the pull request.
      options:
        - label: I have performed a self-review of my own code
          required: true
        - label: I have commented my code, particularly in hard-to-understand areas
          required: true
        - label: I have tested my changes to ensure they are effective
          required: true
        - label: My changes do not introduce any breaking changes
          required: true
        - label: I have checked that my pull request targets the correct branch
          required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this pull request, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
