# Installation:
# https://hub.docker.com/r/1password/connect-api
# https://hub.docker.com/r/1password/connect-sync

services:
  op-connect-api:
    image: 1password/connect-api:1.7
    container_name: op-connect-api
    restart: unless-stopped
    ports:
      - 6151:8080
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - data:/home/opuser/.op/data
    networks:
      - proxy

  op-connect-sync:
    image: 1password/connect-sync:1.7
    container_name: op-connect-sync
    ports:
      - 6152:8080
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - data:/home/opuser/.op/data
    networks:
      - proxy

volumes:
  data:

networks:
  proxy:
    driver: bridge
    external: true
