# Installation: https://hub.docker.com/r/robhaswell/squid-authenticated

services:
  squid:
    image: robhaswell/squid-authenticated
    container_name: squid-auth
    environment:
      - SQUID_USERNAME=${SQUID_USERNAME}
      - SQUID_PASSWORD=${SQUID_PASSWORD}
    ports:
      - 3588:3128
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
