# Installation: https://hub.docker.com/r/coderaiser/cloudcmd

services:
  cloudcmd:
    image: coderaiser/cloudcmd:17.4.2
    container_name: cloudcmd
    ports:
      - 2861:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
