version: '3'
services:
  cloudcmd:
    image: coderaiser/cloudcmd:16.18.0
    container_name: cloudcmd
    hostname: cloudcmd

    ports:
      - 2861:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
