---
version: '3.4'
services:
  authentik:
    image: beryju/authentik:2023.4
    container_name: authentik
    hostname: authentik
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql-authentik
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_ERROR_REPORTING__ENABLED: 'true'
      AUTHENTIK_SECRET_KEY: '${AUTHENTIK_SECRET_KEY}'
      AUTHENTIK_AUTHENTIK__GEOIP: '/geoip/GeoLite2-City.mmdb' # Optional
      GEOIPUPDATE_ACCOUNT_ID: '${GEOIPUPDATE_ACCOUNT_ID}' # Optional
      GEOIPUPDATE_LICENSE_KEY: '${GEOIPUPDATE_LICENSE_KEY}' # Optional
    volumes:
      - /mnt/appdata/authentik/media:/media
      - /mnt/appdata/authentik/custom-templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/appdata/authentik/geoip:/geoip # Optional
    ports:
      - '9815:9000'
      - '9816:9443'
    networks:
      - proxy

  worker:
    image: beryju/authentik:2023.4
    container_name: authentik_worker
    hostname: authentik_worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql-authentik
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_ERROR_REPORTING__ENABLED: 'true'
      AUTHENTIK_SECRET_KEY: '${AUTHENTIK_SECRET_KEY}'
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore.
    user: root
    volumes:
      - /mnt/appdata/authentik/media:/media
      - /mnt/appdata/authentik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/appdata/authentik/custom-templates:/templates
    networks:
      - proxy

  geoipupdate: # Optional
    image: 'maxmindinc/geoipupdate:v5.0'
    container_name: geoipupdate
    hostname: geoipupdate
    volumes:
      - '/mnt/appdata/geoip:/usr/share/GeoIP'
    environment:
      GEOIPUPDATE_ACCOUNT_ID: '${GEOIPUPDATE_ACCOUNT_ID}'
      GEOIPUPDATE_LICENSE_KEY: '${GEOIPUPDATE_LICENSE_KEY}'
      GEOIPUPDATE_EDITION_IDS: 'GeoLite2-City'
      GEOIPUPDATE_FREQUENCY: '8'
      GEOIPUPDATE_HOST: 'updates.maxmind.com'
    networks:
      - proxy # ---------

  postgres:
    image: postgres:15-bullseye # Only this version works with Authentik, if another version then the following will occur: `Postgres - REQUIRES 10 or up`
    container_name: postgresql-authentik
    hostname: postgresql-authentik
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:8080
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
