# Installation: https://hub.docker.com/r/amir20/dozzle

version: '3.9'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.4.1
    environment:
      - DOZZLE_HOSTNAME=${DOZZLE_HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2123:8080
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
