version: "3.8"
services:
  cloudflared:
    build: https://github.com/cloudflare/cloudflared.git
    #image: cloudflared:2022.1.0-arm64
    container_name: cloudflared
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1001
      - PGID=1001
      - TUNNEL_TOKEN=xxx
    volumes:
      - '/mnt/appdata/cloudflared/:/etc/cloudflared/'
#    extra_hosts:
#      - "vps.domain.com:127.0.0.1"                  # Only necessary on some VPS machines if Cloudflared does not connect properly.
