# Installation: https://hub.docker.com/r/cloudflare/cloudflared

version: '3.9'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    command: tunnel run --config /etc/cloudflared/config.yml --token ${CLOUDFLARED_TUNNEL_TOKEN}
    volumes:
      - ./config/:/etc/cloudflared/
    networks:
      - proxy
#    extra_hosts:
#      - "vps.domain.com:127.0.0.1"

# ^ Only necessary on some VPS machines if Cloudflared does not connect properly.
# (domain/sub domain that contains the same tunnelID)
networks:
  proxy:
    driver: bridge
    external: true
