version: '3.9'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    command: tunnel run --token ${CLOUDFLARED_TUNNEL_TOKEN} 
    environment:
      - PUID=${CLOUDFLARED_PUID}
      - PGID=${CLOUDFLARED_PGID}
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    volumes:
      - /mnt/appdata/cloudflared/:/etc/cloudflared/
#    extra_hosts:
#      - "vps.domain.com:127.0.0.1"                  # Only necessary on some VPS machines if Cloudflared does not connect properly.
