version: '3.9'
services:
  browserless:
    image: browserless/chrome:1-puppeteer-1.20.0
    container_name: browserless
    hostname: browserless
    environment:
      - DEBUG=${BROWSERLESS_DEBUG}
      - MAX_CONCURRENT_SESSIONS=${BROWSERLESS_MAX_CONCURRENT_SESSIONS}
      - MAX_QUEUE_LENGTH=${BROWSERLESS_MAX_QUEUE_LENGTH}
      - WORKSPACE_DIR=${BROWSERLESS_WORKSPACE_DIR}
      - ENABLE_DEBUGGER=${BROWSERLESS_ENABLE_DEBUGGER}
      - ENABLE_CORS=${BROWSERLESS_ENABLE_CORS}
      - EXIT_ON_HEALTH_FAILURE=${BROWSERLESS_EXIT_ON_HEALTH_FAILURE}
      - METRICS_JSON_PATH=${BROWSERLESS_METRICS_JSON_PATH}
      - PREBOOT_CHROME=${BROWSERLESS_PREBOOT_CHROME}
      - KEEP_ALIVE=${BROWSERLESS_KEEP_ALIVE}
      - CHROME_REFRESH_TIME=${BROWSERLESS_CHROME_REFRESH_TIME}
      - DEFAULT_IGNORE_HTTPS_ERRORS=${BROWSERLESS_DEFAULT_IGNORE_HTTPS_ERRORS}
      - DEFAULT_BLOCK_ADS=${BROWSERLESS_DEFAULT_BLOCK_ADS}
    ports:
      - 8354:3000
    volumes:
      - /opt/appdata/browserless/downloads:/downloads
      - /opt/appdata/browserless/root:/root/metrics.json
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
