# Installation: https://hub.docker.com/_/adminer

version: '3.9'
services:
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8686:8080
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
