version: '3.9'
services:
  solr:
    image: solr:9.4.1
    container_name: solr
    hostname: solr
    ports:
      - 8626:8983
    volumes:
      - /mnt/appdata/solr:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
