version: '3.9'
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    environment:
      - WG_HOST=some.example.com
      - PASSWORD=some-password
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.60.10
    volumes:
      - .:/etc/wireguard
    ports:
      - '1034:51820/udp'
      - '1035:51821/tcp'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - proxy

networks:
  proxy: # rename this to your custom docker network.
    driver: bridge
    external: true
