version: '3.9'
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    environment:
      - WG_HOST=${WG_EASY_WG_HOST}
      - PASSWORD=${WG_EASY_PASSWORD}
      - WG_PORT=${WG_EASY_WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_EASY_WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_EASY_WG_DEFAULT_DNS}
    volumes:
      - .:/etc/wireguard
    ports:
      - 1034:51820/udp
      - 1035:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - proxy

networks:
  proxy: # rename this to your custom docker network.
    driver: bridge
    external: true
