#
# https://github.com/Tyrrrz/DiscordChatExporter/blob/master/.docs/Getting-started.md#exportguild
#

version: '3.9'
services:
  discordchatexporter:
    image: tyrrrz/discordchatexporter:stable
    container_name: discordchatexporter
    restart: unless-stopped
    volumes:
      - /opt/appdata/discord/chat-exporter:/out
    environment:
      - DISCORD_TOKEN=${DISCORDCHATEXPORTER_DISCORD_TOKEN}
      - DISCORD_TOKEN_BOT=${DISCORDCHATEXPORTER_DISCORD_TOKEN_BOT}
    command: exportguild -g DISCORD_SERVER_ID --dateformat "dd/MM/yyyy HH:mm"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
