# Installation: https://hub.docker.com/r/tecnativa/docker-socket-proxy

version: '3.9'
services:
  dockersocket:
    image: tecnativa/docker-socket-proxy
    container_name: dockersocket
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
