version: '3'
services:
  putty:
    container_name: putty
    image: jlesage/putty:v1.4.0
    hostname: putty
    environment:
      - TZ=America/NewYork
      - DISPLAY_WIDTH= 1920
      - DISPLAY_HEIGHT=1080
      - SECURE_CONNECTION=1
      - ENABLE_CJK_FONT=1
      - PUID=1000
      - PGID=1000
      - UMASK=000 # Mask that controls how file permissions are set for newly created files. The value of the mask is in octal notation.
    ports:
      - "7818:5800"
      - "7916:5900"
    volumes:
      - /mnt/appdata/putty:/config:rw
    restart: unless-stopped
    networks:
      - proxy
      
networks:
  proxy:
    driver: bridge
    external: true