http:
  routers:
    ###############################################################################################################################################################################

    ## EXTERNAL ROUTING ##
    traefik:
      entryPoints:
        - https
      rule: 'Host(`traefik.domain.com`)'
      service: traefik
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #FreeIPA routing
    freeipa:
      entryPoints:
        - https
      rule: 'Host(`ipa.domain.com`)'
      service: freeipa
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Authentik auth routing
    authentik:
      entryPoints:
        - https
      rule: 'Host(`auth.domain.com`)'
      service: authentik-auth
      middlewares:
        - 'securityHeaders'

    #VSCode routing
    vscode:
      entryPoints:
        - https
      rule: 'Host(`vscode.domain.com`)'
      service: vscode
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Organizrv2 routing
    organizr:
      entryPoints:
        - https
      rule: 'Host(`organizr.domain.com`)'
      service: organizr
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #ApacheGuacamole routing
    guacamole:
      entryPoints:
        - https
      rule: 'Host(`guacamole.domain.com`)'
      service: guacamole
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Webtop routing
    webtop:
      entryPoints:
        - https
      rule: 'Host(`webtop.domain.com`)'
      service: webtop
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #HomeChart routing
    homechart:
      entryPoints:
        - https
      rule: 'Host(`tasks.domain.com`)'
      service: homechart
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Bookstack routing
    bookstack:
      entryPoints:
        - https
      rule: 'Host(`docstack.domain.com`)'
      service: bookstack
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #InfluxDB routing
    influxdb:
      entryPoints:
        - https
      rule: 'Host(`influx.domain.com`)'
      service: influxdb
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #VaultWarden routing
    vwarden:
      entryPoints:
        - https
      rule: 'Host(`vwarden.domain.com`)'
      service: vwarden
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Grafana routing
    grafana:
      entryPoints:
        - https
      rule: 'Host(`graf.domain.com`)'
      service: grafana
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Uptime_Kuma routing
    ukuma:
      entryPoints:
        - https
      rule: 'Host(`ukuma.domain.com`)'
      service: ukuma
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Mesh_Central routing
    meshc:
      entryPoints:
        - https
      rule: 'Host(`mesh.domain.com`)'
      service: meshc
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Dozzle routing
    dozzle:
      entryPoints:
        - https
      rule: 'Host(`dozzle.domain.com`)'
      service: dozzle
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Cryptgeon routing
    cryptgeon:
      entryPoints:
        - https
      rule: 'Host(`crypt.domain.com`)'
      service: cryptgeon
      middlewares:
        - 'securityHeaders'
        #- "authentik-auth"

    #Firefly-iii routing
    firefly:
      entryPoints:
        - https
      rule: 'Host(`firefly.domain.com`)'
      service: firefly
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

    #Pterodactyl-panel routing
    pterodactyl-panel:
      entryPoints:
        - https
      rule: 'Host(`pterodactyl-panel.domain.com`)'
      service: pterodactyl-panel
      middlewares:
        - 'securityHeaders'
        - 'corsAll@file'

    #Pterodactyl-wings/node routing
    pterodactyl-wing:
      entryPoints:
        - https
      rule: 'Host(`pterodactyl-wings.domain.com`)'
      service: pterodactyl-wings
      middlewares:
        - 'securityHeaders'
        - 'corsAll@file'

    #Syncthing service
    syncthing:
      entryPoints:
        - https
      rule: 'Host(`syncthing.domain.com`)'
      service: syncthing
      middlewares:
        - 'securityHeaders'
        - 'authentik-auth'

  #    homeassistant:
  #      entryPoints:
  #        - https
  #      rule: 'Host(`homeassistant.domain.com`)'
  #      service: homeassistant
  #      middlewares:
  #        - "securityHeaders"
  #        - "authentik-auth"

  ########################################################################################################################################################################

  ## SERVICES ##
  services:
    # Traefik service
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080

    # FreeIPA service
    freeipa:
      loadbalancer:
        servers:
          - url: 'https://IPv4:443'

    # Authentic auth service
    authentik-auth:
      loadbalancer:
        servers:
          - url: http://authentik:9000

    # VSCode service
    vscode:
      loadbalancer:
        servers:
          - url: http://hostname:1431

    # OrganizrV2 service
    organizr:
      loadbalancer:
        servers:
          - url: http://hostname:9284

    # ApacheGuacamole service
    guacamole:
      loadbalancer:
        servers:
          - url: http://hostname:8383

    # Webtop service
    webtop:
      loadbalancer:
        servers:
          - url: http://hostname:3050

    # Homechart service
    homechart:
      loadbalancer:
        servers:
          - url: 'http://hostname:3040'

    # Bookstack service
    bookstack:
      loadbalancer:
        servers:
          - url: http://hostname:6875

    # InfluxDB service
    influxdb:
      loadbalancer:
        servers:
          - url: https://hostname:8086

    # Vault Warden service
    vwarden:
      loadbalancer:
        servers:
          - url: http://vaultwarden:80

    # Grafana service
    grafana:
      loadbalancer:
        servers:
          - url: http://hostname:3421

    # Uptime_Kuma service
    ukuma:
      loadbalancer:
        servers:
          - url: http://hostname:3001

    # Mesh_Central service
    meshc:
      loadbalancer:
        servers:
          - url: https://hostname:8089

    # Dozzle
    dozzle:
      loadbalancer:
        servers:
          - url: http://hostname:2123

    # Cryptgeon
    cryptgeon:
      loadbalancer:
        servers:
          - url: http://hostname:5800

    # Firefly-iii
    firefly:
      loadbalancer:
        servers:
          - url: http://hostname:6353

    #Pterodactyl-panel routing
    pterodactyl-panel:
      loadbalancer:
        servers:
          - url: http://hostname:8025

    #Pterodactyl-wings/node  routing
    pterodactyl-wings:
      loadbalancer:
        servers:
          - url: http://hostname:8026

    # Syncthing service
    syncthing:
      loadbalancer:
        servers:
          - url: http://syncthing:8384

  ###############################################################################################################################################################################

  ## MIDDLEWARES ##
  middlewares:
    # Authentik guard
    authentik-auth:
      forwardauth:
        address: http://authentik:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version

    # # Authelia guard
    # auth:
    #   forwardauth:
    #     address: http://authelia:9091/api/verify?rd=https://auth.domain.com/
    #     trustForwardHeader: true
    #     authResponseHeaders:
    #       - Remote-User
    #       - Remote-Groups
    #       - Remote-Name
    #       - Remote-Email

    # # Authelia basic auth guard
    # auth-basic:
    #   forwardauth:
    #     address: http://authelia:9091/api/verify?auth=basic
    #     trustForwardHeader: true
    #     authResponseHeaders:
    #       - Remote-User
    #       - Remote-Groups
    #       - Remote-Name
    #       - Remote-Email

    # Pterodactyl corsALL
    corsAll:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: 'https'
        customResponseHeaders:
          X-Forwarded-Proto: 'https'
        accessControlAllowMethods:
          - OPTION
          - POST
          - GET
          - PUT
          - DELETE
        accessControlAllowHeaders:
          - '*'
        accessControlAllowOriginList:
          - '*'
        accessControlMaxAge: 100
        addVaryHeader: true

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: 'none,noarchive,nosnippet,notranslate,noimageindex'
          server: ''
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: 'same-origin'
        hostsProxyHeaders:
          - 'X-Forwarded-Host'
        customRequestHeaders:
          X-Forwarded-Proto: 'https'
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true

    traefik-real-ip:
      plugin:
        traefik-real-ip:
          excludednets: 1.1.1.1/24
