version: '3.9'
services:
  joplin:
    container_name: joplin
    image: etechonomy/joplin-server:2.10.10
    hostname: joplin
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=https://joplin.domain.com
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin-postgres
      - MAILER_ENABLED=1
      - MAILER_HOST=smtp.gmail.com
      - MAILER_PORT=465
      - MAILER_SECURE=1
      - MAILER_AUTH_USER=something@email.com
      - MAILER_AUTH_PASSWORD=xxx
      - MAILER_NOREPLY_NAME=JoplinServer
      - MAILER_NOREPLY_EMAIL=noreply@domain.com
    ports:
      - "22300:22300"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy

  joplin-postgres:
      image: postgres:15.3
      container_name: joplin-postgres
      hostname: joplin-postgres
      volumes:
          - /mnt/appdata/joplin-postgres:/var/lib/postgresql/data
      ports:
          - "5255:5432"
      restart: unless-stopped
      environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DATABASE}
      labels:
        - com.centurylinklabs.watchtower.enable=true
      networks:
        - proxy
      
networks:
  proxy:
    driver: bridge
    external: true