# Use root/example as user/password credentials

version: '3.1'
services:
  adminer:
    image: adminer:4.8.1
    hostname: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8686:8080
    networks:
      - proxymoxy

networks:
  proxymoxy:
    driver: bridge
    external: true

