version: '3.9'

services:
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    hostname: ntp
    environment:
      - NTP_SERVERS=${NTP_SERVERS}
    restart: unless-stopped
    ports:
      - 1016:123/udp
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
