version: '3.9'
services:
  homechart:
    container_name: homechart
    hostname: homechart
    image: candiddev/homechart:latest
    environment:
      - HOMECHART_POSTGRESQL_HOSTNAME=${HOMECHART_POSTGRESQL_HOSTNAME}
      - HOMECHART_POSTGRESQL_PORT=${HOMECHART_POSTGRESQL_PORT}
      - HOMECHART_POSTGRESQL_PASSWORD=${HOMECHART_POSTGRESQL_PASSWORD}
      - HOMECHART_POSTGRESQL_USERNAME=${HOMECHART_POSTGRESQL_USERNAME}
      - HOMECHART_POSTGRESQL_SSLMODE=${HOMECHART_POSTGRESQL_SSLMODE}
      - HOMECHART_POSTGRESQL_DATABASE=${HOMECHART_POSTGRESQL_DATABASE}
      - HOMECHART_CACHE_REDISHOSTNAME=${HOMECHART_CACHE_REDISHOSTNAME}
      - HOMECHART_CACHE_REDISPORT=${HOMECHART_CACHE_REDISPORT}
      - HOMECHART_CACHE_REDISPASSWORD=${HOMECHART_CACHE_REDISPASSWORD}
      - HOMECHART_CACHE_REDISDATABASE=${HOMECHART_CACHE_REDISDATABASE}
      - HOMECHART_APP_ADMINEMAILADDRESSES=${HOMECHART_APP_ADMINEMAILADDRESSES}
      - HOMECHART_APP_SIGNUPDISABLED=${HOMECHART_APP_SIGNUPDISABLED}
      - HOMECHART_APP_BASEURL=${HOMECHART_APP_BASEURL}
      - HOMECHART_APP_DEBUG=${HOMECHART_APP_DEBUG}
      - HOMECHART_APP_KEEPCALENDAREVENTDAYS=${HOMECHART_APP_KEEPCALENDAREVENTDAYS}
      - HOMECHART_APP_KEEPCOOKSCHEDULEDAYS=${HOMECHART_APP_KEEPCOOKSCHEDULEDAYS}
      - HOMECHART_APP_KEEPDELETEDDAYS=${HOMECHART_APP_KEEPDELETEDDAYS}
      - HOMECHART_APP_KEEPPLANTASKDAYS=${HOMECHART_APP_KEEPPLANTASKDAYS}
      - HOMECHART_APP_KEEPWIKIPAGEVERSIONS=${HOMECHART_APP_KEEPWIKIPAGEVERSIONS}
      - HOMECHART_APP_MOTD=${HOMECHART_APP_MOTD}
      - HOMECHART_SMTP_EMAILADDRESS=${HOMECHART_SMTP_EMAILADDRESS}
      - HOMECHART_SMTP_HOSTNAME=${HOMECHART_SMTP_HOSTNAME}
      - HOMECHART_SMTP_REPLYTO=${HOMECHART_SMTP_REPLYTO}
      - HOMECHART_SMTP_PORT=${HOMECHART_SMTP_PORT}
      - HOMECHART_SMTP_USERNAME=${HOMECHART_SMTP_USERNAME}
      - HOMECHART_SMTP_PASSWORD=${HOMECHART_SMTP_PASSWORD}
    ports:
      - 3040:3000
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
