version: '3.9'

services:
  homechart:
    container_name: homechart
    hostname: homechart
    image: candiddev/homechart:latest
    environment:
      HOMECHART_POSTGRESQL_HOSTNAME: postgres
      HOMECHART_POSTGRESQL_PORT: 5432
      HOMECHART_POSTGRESQL_PASSWORD: ${HOMECHART_POSTGRESQL_PASSWORD}
      HOMECHART_POSTGRESQL_USERNAME: postgres
      HOMECHART_POSTGRESQL_SSLMODE: 'disable'
      HOMECHART_POSTGRESQL_DATABASE: homechart

      HOMECHART_CACHE_REDISHOSTNAME: redis
      HOMECHART_CACHE_REDISPORT: 6379
      HOMECHART_CACHE_REDISPASSWORD: ${HOMECHART_CACHE_REDISPASSWORD}

      HOMECHART_CACHE_REDISDATABASE: 1

      HOMECHART_APP_ADMINEMAILADDRESSES: ${HOMECHART_APP_ADMINEMAILADDRESSES}
      HOMECHART_APP_SIGNUPDISABLED: 'false'

      HOMECHART_APP_BASEURL: ${HOMECHART_APP_BASEURL}
      HOMECHART_APP_DEBUG: 'true'
      HOMECHART_APP_KEEPCALENDAREVENTDAYS: 180
      HOMECHART_APP_KEEPCOOKSCHEDULEDAYS: 365
      HOMECHART_APP_KEEPDELETEDDAYS: 32
      HOMECHART_APP_KEEPPLANTASKDAYS: 90
      HOMECHART_APP_KEEPWIKIPAGEVERSIONS: 10
      HOMECHART_APP_MOTD: 'Tasks/Lists/Recipies'

      HOMECHART_SMTP_EMAILADDRESS: ${HOMECHART_SMTP_EMAILADDRESS}
      HOMECHART_SMTP_HOSTNAME: smtp.gmail.com
      HOMECHART_SMTP_REPLYTO: ${HOMECHART_SMTP_REPLYTO}
      HOMECHART_SMTP_PORT: 587
      HOMECHART_SMTP_USERNAME: ${HOMECHART_SMTP_USERNAME}
      HOMECHART_SMTP_PASSWORD: ${HOMECHART_SMTP_PASSWORD}

    ports:
      - '3040:3000'
    restart: unless-stopped

    networks:
      - proxym

networks:
  proxy:
    driver: bridge
    external: true
