version: '3.1'
services:
  postgres:
    image: postgres:15.3
    container_name: postgresql
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:8080
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
