version: '3.9'
services:

  db-backup:
    image: tiredofit/db-backup:3.9.10
    container_name: db-backup
    hostname: db-backup

    volumes:
      - /mnt/backups/databases/db-backup:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:                                                  # https://github.com/tiredofit/docker-db-backup#environment-variables
      - MODE=${DB_BACKUP_MODE}
      - BACKUP_LOCATION=${DB_BACKUP_BACKUP_LOCATION}
      - SPLIT_DB=${DB_BACKUP_SPLIT_DB}
      - COMPRESSION=${DB_BACKUP_COMPRESSION}
      - ENABLE_CHECKSUM=${DB_BACKUP_ENABLE_CHECKSUM}
      - CHECKSUM=${DB_BACKUP_CHECKSUM}
      - TIMEZONE=${DB_BACKUP_TIMEZONE}
      - DB_DUMP_BEGIN=${DB_BACKUP_DB_DUMP_BEGIN}
      - DB_CLEANUP_TIME=${DB_BACKUP_DB_CLEANUP_TIME}
      - DB_TYPE=${DB_BACKUP_DB_TYPE}
      - DB_HOST=${DB_BACKUP_DB_HOST}
      - DB_NAME=${DB_BACKUP_DB_NAME}
      - DB_USER=${DB_BACKUP_DB_USER}
      - DB_PASS=${DB_BACKUP_DB_PASS}
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
