version: '3.9'
services:
  syncthing:
    image: linuxserver/syncthing:1.27.2
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${SYNCTHING_PUID}
      - PGID=${SYNCTHING_PGID}
      - TZ=${SYNCTHING_TZ}
    volumes:
      - /opt/appdata/syncthing/config:/config
      - /opt/appdata/:/machine-appdata
    ports:
      - 1020:8384
      - 1021:22000
      - 1022:21027/udp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
