version: "3.9"
services:
  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo:4.2.21
    volumes:
      - /mnt/appdata/mongodb/data:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true