version: '2.0'
services:
  guacamole:
    container_name: guacamole
    image: oznu/guacamole:armhf
    hostname: guacamole
    ports:
      - 8383:8080
    volumes:
      - /mnt/appdata/guacamole:/config
    restart: unless-stopped
    networks:
      - proxy
  
networks:
  proxy:
    driver: bridge
    external: true
