# Installation: https://hub.docker.com/r/linuxserver/duplicati

version: '3.9'
services:
  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati:2.0.8
    hostname: duplicati
    environment:
      - PUID=${DUPLICATI_PUID}
      - PGID=${DUPLICATI_PGID}
      - TZ=${DUPLICATI_TZ}
      #- CLI_ARGS=${DUPLICATI_CLI_ARGS}  #optional
    volumes:
      - /opt/appdata/duplicati/config:/config
      - /opt/appdata/duplicati/backups:/backups
      - /opt/appdata/duplicati/source:/source
    ports:
      - 3415:8200
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
