version: '3.1'

services:
  postgres:
    image: postgres:14.4
    container_name: postgresql
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:8080
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
