#
# https://github.com/linuxserver/docker-grocy
# https://github.com/grocy/grocy-docker/blob/main/docker-compose.yml
#

version: '3.9'
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=${GROCY_PUID}
      - PGID=${GROCY_PGID}
      - TZ=${GROCY_TZ}
    volumes:
      - /opt/appdata/grocy/data:/config
    ports:
      - 9283:80
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
