tunnel: tunnel_id
credentials-file: /home/nonroot/.cloudflared/tunnel_id.json

# NOTE: You should only have one ingress tag, so if you uncomment one block comment the others

#forward all traffic to Reverse Proxy w/ SSL
ingress:
  - service: https://IPv4:44301
    originRequest:
      originServerName: traefik.domain.com
#forward all traffic to Reverse Proxy w/ SSL and no TLS Verify
#ingress:
#  - service: https://IPv4:44301
#    originRequest:
#      noTLSVerify: true

# forward all traffic to reverse proxy over http
#ingress:
#  - service: http://REVERSEPROXYIP:PORT
