# Installation: https://kasmweb.com/docs/latest/guide/custom_images.html

services:
  kasmweb-discord:
    image: kasmweb/discord:1.15.0-rolling
    container_name: kasmweb-discord
    restart: unless-stopped
    shm_size: 1024m
    environment:
      - VNC_PW=${KASMWEB_DISCORD_VNC_PW}
    ports:
      - 1039:6901
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
