version: '3.9'
services:
  kasmweb-discord:
    image: kasmweb/discord:1.15.0-rolling
    hostname: kasmweb-discord
    container_name: kasmweb-discord
    restart: unless-stopped
    shm_size: 1024m
    environment:
      - VNC_PW=${KASMWEB_DISCORD_VNC_PW}
    ports:
      - 1039:6901
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
