# Installation: https://hub.docker.com/r/pawelmalak/flame
version: '3.9'
services:
  flame:
    image: pawelmalak/flame:multiarch2.3.0
    container_name: flame
    volumes:
      - /opt/appdata/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
    ports:
      - 5030:5005
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
