version: '3.9'
services:
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr:2.00.20.1
    hostname: tdarr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 1024:8265 # webUI port
      - 1025:8266 # server port
      - 1026:8267 # Internal node port
    environment:
      - TZ=${TDARR_TZ}
      - PUID=${TDARR_PUID}
      - PGID=${TDARR_PGID}
      - UMASK_SET=${TDARR_UMASK_SET}
      - serverIP=${TDARR_serverIP}
      - serverPort=${TDARR_serverPort}
      - webUIPort=${TDARR_webUIPort}
      - internalNode=${TDARR_internalNode}
      - nodeID=${TDARR_nodeID}
      - nodeIP=${TDARR_nodeIP}
      - nodePort=${TDARR_nodePort}
      - NVIDIA_DRIVER_CAPABILITIES=${TDARR_NVIDIA_DRIVER_CAPABILITIES}
      - NVIDIA_VISIBLE_DEVICES=${TDARR_NVIDIA_VISIBLE_DEVICES}
    volumes:
      - /path/to/server:/app/server
      - /path/to/configs:/app/configs
      - /path/to/logs:/app/logs
      - /path/to/media/:/media
      - /path/to/temp/:/temp
    labels:
      - com.centurylinklabs.watchtower.enable=true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    networks:
      - proxy

networks:
  proxy: # rename this to your custom docker network.
    driver: bridge
    external: true
