---
version: "2.1"
services:
  endlessh:
    image: linuxserver/endlessh:version-dfe44eb2
    container_name: endlessh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/NewYork
      - MSDELAY=10000 #optional
      - MAXLINES=32 #optional
      - MAXCLIENTS=4096 #optional
      - LOGFILE=false #optional
      - BINDFAMILY= #optional
    volumes:
      - /mnt/appdata/endlessh:/config #optional
    ports:
      - 33:2222
    restart: unless-stopped
    networks:
      - proxy
      
networks:
  proxy:
    driver: bridge
    external: true