# Installation: https://hub.docker.com/r/tonistiigi/binfmt

version: '3.9'
services:
  binfmt:
    image: tonistiigi/binfmt:latest
    container_name: binfmt
    command: --install all
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
