version: '3.9'
services:
  floatplane-downloader:
    image: inrix/floatplane-downloader
    container_name: floatplane-downloader
    hostname: floatplane-downloader
    volumes:
      - /opt/appdata/floatplanedownloader/db:/fp/db
      - /opt/appdata/media:/fp/videos
    tty: true # To be able to reply to interactive prompts.
    stdin_open: true # For interactive flag.
    restart: unless-stopped
    environment:
      - headless=${FLOATPLANE_DOWNLOADER_headless}
      - PUID=${FLOATPLANE_DOWNLOADER_PUID}
      - PGID=${FLOATPLANE_DOWNLOADER_PGID}
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
