# Installation: https://hub.docker.com/r/kasmweb/core-ubuntu-bionic

version: '3.9'
services:
  core-ubuntu-bionic:
    image: kasmweb/core-ubuntu-bionic:1.15.0-rolling
    container_name: core-ubuntu-bionic
    restart: unless-stopped
    shm_size: 2048m
    environment:
      - VNC_PW=${CORE_UBUNTU_BIONIC_VNC_PW}
    ports:
      - 1038:6901
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
