---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack:22.11.20221130
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.DOMAIN.COM
      - DB_HOST=mariadb
      - DB_USER=bookstack
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=bookstack
      - MAIL_DRIVER=smtp

      # Host, Port & Encryption mechanism to use
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_ENCRYPTION=tls

      # Authentication details for your SMTP service
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

      # The "from" email address for outgoing email
      - MAIL_FROM=${MAIL_FROM}

      # The "from" name used for outgoing email
      - MAIL_FROM_NAME=BookStack
      - QUEUE_CONNECTION=database
    volumes:
      - /mnt/appdata/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
