---
- name: 1Password CLI Tool
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Download 1Password CLI tool for arm64
      unarchive:
        src: 'https://cache.agilebits.com/dist/1P/op2/pkg/v2.6.2/op_linux_arm64_v2.6.2.zip'
        remote_src: yes
        dest: /tmp
      when: ansible_architecture == "aarch64"

    - name: Download 1Password CLI tool for amd64
      unarchive:
        src: 'https://cache.agilebits.com/dist/1P/op2/pkg/v2.6.2/op_linux_amd64_v2.6.2.zip'
        remote_src: yes
        dest: /tmp
      when: ansible_architecture == "x86_64"

    - name: Copy 1Password CLI tool into place
      copy:
        src: /tmp/op
        dest: /usr/local/bin/op
        mode: 0755
        owner: root
        group: root

    - name: Update 1Password CLI tool
      command: op update
      become: true

    - name: 1Password Login
      become: no
      expect:
        command: 'op signin {{ op.address }} {{ op.email }} {{ op_secret }}'
        responses:
          (?i)password: '{{ op_pass }}'

  vars_prompt:
    - name: op.email
      prompt: What is your 1Password email?

    - name: op_secret
      prompt: What is your 1Password secret key?

    - name: op_pass
      prompt: What is your 1Password password?
