---
- hosts: all
  vars_prompt:
    - name: 'DockerNetworkName'
      prompt: 'Enter the name of the docker network.'
      private: no
  tasks:
    - name: Create "{{ DockerNetworkName }}" Docker network
      docker_network:
        name: '{{ DockerNetworkName }}'
        state: present
      become: true
