---
- name: Set timezone and configure timesyncd
  hosts: all
  become: true
  vars_prompt:
    - name: 'timezone'
      prompt: 'Enter your timezone (e.g. America/New_York)'
      private: no
    - name: 'ntp_server'
      prompt: 'Enter your NTP server IP (e.g. 192.168.0.100)'
      private: no

  tasks:
    - name: set timezone
      shell: timedatectl set-timezone {{ timezone }}

    - name: Make sure timesyncd is stopped
      systemd:
        name: systemd-timesyncd.service
        state: stopped

    - name: Copy over the timesyncd config
      template:
        src: ../templates/timesyncd.conf
        dest: /etc/systemd/timesyncd.conf
      vars:
        ntp_server: '{{ ntp_server }}'

    - name: Make sure timesyncd is started
      systemd:
        name: systemd-timesyncd.service
        state: started
