version: '3'
services:
  dupeguru:
    container_name: dupeguru
    image: jlesage/dupeguru:v1.12.1
    hostname: dupeguru
    environment:
      - TZ=America/NewYork
      - DISPLAY_WIDTH= 1920
      - DISPLAY_HEIGHT=1080
      - SECURE_CONNECTION=1
      - ENABLE_CJK_FONT=1
      - UMASK=000 # Mask that controls how file permissions are set for newly created files. The value of the mask is in octal notation.
    ports:
      - "57801:5800"
      - "7901:5900"
    volumes:
      - "/mnt/appdata/dupeguru:/config:rw"
      - "/mnt/appdata/dupeguru/storage:/storage:rw"
    restart: unless-stopped
    networks:
      - proxy
      
networks:
  proxy:
    driver: bridge
    external: true