version: '3.9'
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${WIREGUARD_PUID}
      - PGID=${WIREGUARD_PGID}
      - TZ=${WIREGUARD_TZ}
      - SERVERURL=${WIREGUARD_SERVERURL}
      - SERVERPORT=${WIREGUARD_SERVERPORT}
      - PEERS=${WIREGUARD_PEERS}
      - PEERDNS=${WIREGUARD_PEERDNS}
      - INTERNAL_SUBNET=${WIREGUARD_INTERNAL_SUBNET}
      - ALLOWEDIPS=${WIREGUARD_ALLOWEDIPS}
    volumes:
      - /mnt/appdata/wireguard/config:/config
      - /mnt/appdata/wireguard/lib/modules:/lib/modules
    ports:
      - 1037:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy: # rename this to your custom docker network.
    driver: bridge
    external: true
