version: '2.1'
services:
  pwdpush:
    container_name: pwdpush
    image: pglombardo/pwpush-postgres:1.28.6
    hostname: pwdpush
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '5100:5100'
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
