version: '3.9'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.1.2-ce.0
    hostname: gitlab-ce
    container_name: gitlab-ce
    privileged: true
    environment:
      - GITLAB_OMNIBUS_CONFIG=${GITLAB_OMNIBUS_CONFIG}
    ports:
      - 1011:22
      - 1012:80
      - 1013:443
    volumes:
      - $GITLAB_HOME/config:/etc/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/data:/var/opt/gitlab
    shm_size: 256m
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
