version: '3.9'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.8.1-ce.0
    hostname: gitlab-ce
    container_name: gitlab-ce
    privileged: true
    environment:
      - GITLAB_OMNIBUS_CONFIG=${GITLAB_OMNIBUS_CONFIG}
    ports:
      - 1011:22
      - 1012:80
      - 1013:443
    volumes:
      - /mnt/appdata/gitlab/config:/etc/gitlab
      - /mnt/appdata/gitlab/logs:/var/log/gitlab
      - /mnt/appdata/gitlab/data:/var/opt/gitlab
    shm_size: 256m
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
