version: '3.9'
services:
  nut:
    image: teknologist/webnut
    container_name: webnut
    hostname: nut
    environment:
      - UPS_HOST=${NUT_UPS_HOST}
      - UPS_PORT=${NUT_UPS_PORT}
      - UPS_USER=${NUT_UPS_USER}
      - UPS_PASSWORD=${NUT_UPS_PASSWORD}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - DockerNetwork
    ports:
      - 1033:6543

networks:
  DockerNetwork: # rename this to your custom docker network.
    driver: bridge
    external: true
