version: '3.3'

services:
  uptime_kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:1.17.1
    hostname: uptime_kuma
    volumes:
      - /mnt/appdata/uptime_kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - proxy
    
networks:
  proxy:
    driver: bridge
    external: true