version: '3.9'
services:
  mrss-bot:
    container_name: mrss-bot
    restart: unless-stopped
    image: synzen/monitorss:latest
    environment:
      - DRSS_START=${MRSS_BOT_DRSS_START}
      - DRSS_BOT_TOKEN=${MRSS_BOT_DRSS_BOT_TOKEN}
      - DRSS_DATABASE_URI=${MRSS_BOT_DRSS_DATABASE_URI}
      - DRSS_FEEDS_TIMEZONE=${MRSS_BOT_DRSS_FEEDS_TIMEZONE}
      - TZ=${MRSS_BOT_TZ}
      - HOST_HOSTNAME=${MRSS_BOT_HOST_HOSTNAME}
      - HOST_CONTAINERNAME=${MRSS_BOT_HOST_CONTAINERNAME}
      - DRSS_FEEDS_REFRESHRATEMINUTES=${MRSS_BOT_DRSS_FEEDS_REFRESHRATEMINUTES}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy

  mrss-web:
    container_name: mrss-web
    hostname: mrss-web
    image: synzen/monitorss
    restart: unless-stopped
    ports:
      - 8519:8081
    environment:
      - DRSS_START=${MRSS_WEB_DRSS_START}
      - DRSSWEB_DATABASE_REDIS=${MRSS_WEB_DRSSWEB_DATABASE_REDIS}
      - DRSSWEB_DATABASE_URI=${MRSS_WEB_DRSSWEB_DATABASE_URI}
      - DRSSWEB_BOT_REDIRECTURI=${MRSS_WEB_DRSSWEB_BOT_REDIRECTURI}
      - DRSSWEB_BOT_CLIENTID=${MRSS_WEB_DRSSWEB_BOT_CLIENTID}
      - DRSSWEB_BOT_CLIENTSECRET=${MRSS_WEB_DRSSWEB_BOT_CLIENTSECRET}
      - DRSSWEB_BOT_TOKEN=${MRSS_WEB_DRSSWEB_BOT_TOKEN}
      - TZ=${MRSS_WEB_TZ}
      - HOST_CONTAINERNAME=${MRSS_WEB_HOST_CONTAINERNAME}
      - DRSS_BOT_TOKEN=${MRSS_WEB_DRSS_BOT_TOKEN}
      - HOST_HOSTNAME=${MRSS_WEB_HOST_HOSTNAME}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
