# Installation: https://hub.docker.com/r/guacamole/guacamole

services:
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.5.5
    ports:
      - 1001:8080
    environment:
      - GUACD_HOSTNAME=${GUACAMOLE_GUACD_HOSTNAME}
      - POSTGRESQL_DATABASE=${GUACAMOLE_POSTGRESQL_DATABASE}
      - POSTGRESQL_HOSTNAME=${GUACAMOLE_POSTGRESQL_HOSTNAME}
      - POSTGRESQL_PORT=${GUACAMOLE_POSTGRESQL_PORT}
      - POSTGRESQL_PASSWORD=${GUACAMOLE_POSTGRESQL_PASSWORD}
      - POSTGRESQL_USER=${GUACAMOLE_POSTGRESQL_USER}
    volumes:
      - /opt/appdata/guacamole:/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
