version: '3.9'
services:
  guacamole:
    container_name: guacamole
    image: maxwaldorf/guacamole:1.5.0
    hostname: guacamole
    ports:
      - 1001:8080
    volumes:
      - /mnt/appdata/guacamole:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
