version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8953:8000
    volumes:
      - /mnt/appdata/tubearchivist/media:/youtube
      - /mnt/appdata/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=IPv4 tubearchivist.domain.com                # set your host name
      - TA_USERNAME=${TA_USERNAME}                                      # your initial TA credentials
      - TA_PASSWORD=${TA_PASSWORD}                                      # your initial TA credentials
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}                            # set password for Elasticsearch
      - TZ=America/New_York                                             # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy

  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    hostname: archivist-redis
    restart: unless-stopped
    ports:
      - 8952:6379
    volumes:
      -  /mnt/appdata/tubearchivist-redis:/data
    depends_on:
      - archivist-es
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy
      
  archivist-es:
    image: bbilly1/tubearchivist-es                         # only for amd64, or use official es 8.7.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"              # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    volumes:
      - /mnt/appdata/tubearchivist-es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy
    
networks:
  proxy:
    driver: bridge
    external: true
