version: '2'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:7.2.1
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD-SHELL, redis-cli ping | grep PONG]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
