version: '3.9'
services:
  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    hostname: grafana
    ports:
      - 1001:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - /mnt/appdata/grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
