version: '3.9'
services:
  putty:
    container_name: putty
    image: jlesage/putty:v24.01.1
    hostname: putty
    environment:
      - TZ=${PUTTY_TZ}
      - DISPLAY_WIDTH=${PUTTY_DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${PUTTY_DISPLAY_HEIGHT}
      - SECURE_CONNECTION=${PUTTY_SECURE_CONNECTION}
      - ENABLE_CJK_FONT=${PUTTY_ENABLE_CJK_FONT}
      - PUID=${PUTTY_PUID}
      - PGID=${PUTTY_PGID}
      - UMASK=${PUTTY_UMASK}
    ports:
      - 7818:5800
      - 7916:5900
    volumes:
      - /opt/appdata/putty:/config:rw
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
