version: '3.9'
services:
  authelia:
    image: authelia/authelia:4.37
    container_name: authelia
    hostname: authelia
    volumes:
      - ./config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=${AUTHELIA_TZ}
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
