version: '3.9'
services:
  openvscode-server:
    image: linuxserver/code-server:4.21.0
    container_name: vscode-server
    hostname: vscode
    environment:
      - PUID=${OPENVSCODE_SERVER_PUID}
      - PGID=${OPENVSCODE_SERVER_PGID}
      - UMASK=${OPENVSCODE_SERVER_UMASK}
      - TZ=${OPENVSCODE_SERVER_TZ}
      - CONNECTION_TOKEN=${OPENVSCODE_SERVER_CONNECTION_TOKEN}
      - CONNECTION_SECRET=${OPENVSCODE_SERVER_CONNECTION_SECRET}
      - SUDO_PASSWORD=${OPENVSCODE_SERVER_SUDO_PASSWORD}
      - SUDO_PASSWORD_HASH=${OPENVSCODE_SERVER_SUDO_PASSWORD_HASH}
      - DEFAULT_WORKSPACE=${OPENVSCODE_SERVER_DEFAULT_WORKSPACE}
    volumes:
      - /mnt/appdata/vscode/config:/config
      - /mnt:/data-compose/appdata_of_containers
      - /home/user:/data-compose/docker_compose
    ports:
      - 1007:8443
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
