version: '3.9'
services:
  vscode:
    image: wolflith/vscode:latest
    build:
      context: .
      dockerfile: dockerfile
    container_name: vscode
    hostname: vscode
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=${TZ:?error}
      # - CONNECTION_TOKEN=${OPENVSCODE_SERVER_CONNECTION_TOKEN}       #optional
      # - CONNECTION_SECRET=${OPENVSCODE_SERVER_CONNECTION_SECRET}     #optional
      - SUDO_PASSWORD=${OPENVSCODE_SERVER_SUDO_PASSWORD}
      # - SUDO_PASSWORD_HASH=${OPENVSCODE_SERVER_SUDO_PASSWORD_HASH}   #optional
      - DEFAULT_WORKSPACE=${OPENVSCODE_SERVER_DEFAULT_WORKSPACE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/vscode/config:/config
      - ./wolflith.code-workspace:/config/workspace/wolflith.code-workspace
      - ../../../:/wolflith
      - /mnt:/mnt
      - /home:/home
    ports:
      - 1007:8443
    restart: unless-stopped
    depends_on:
      - dockersocketvscode
    networks:
      - proxy

  dockersocketvscode:
    container_name: dockersocketvscode
    hostname: dockersocketvscode
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
