# Installation: https://dashy.to/docs/deployment#using-docker-compose

version: '3.9'
services:
  dashy:
    image: lissy93/dashy:2.1.1
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /opt/appdata/dashy/my-config.yml:/app/public/conf.yml
    ports:
      - 4000:80
    # Set any environmental variables
    environment:
      - NODE_ENV=${DASHY_NODE_ENV}
      - UID=${DASHY_UID}
      - GID=${DASHY_GID}
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: [CMD, node, /app/services/healthcheck]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
