# Installation: https://hub.docker.com/r/guacamole/guacd

version: '3.9'
services:
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.4
    volumes:
      - /opt/appdata/guacd/drive:/drive:rw
      - /opt/appdata/guacd/record:/record:rw
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
