version: '2'
services:
  bookstack:
    image: linuxserver/bookstack:23.12.20240115
    container_name: bookstack
    environment:
      - PUID=${BOOKSTACK_PUID}
      - PGID=${BOOKSTACK_PGID}
      - APP_URL=${BOOKSTACK_APP_URL}
      - DB_HOST=${BOOKSTACK_DB_HOST}
      - DB_USER=${BOOKSTACK_DB_USER}
      - DB_PASS=${BOOKSTACK_DB_PASS}
      - DB_DATABASE=${BOOKSTACK_DB_DATABASE}
      - MAIL_DRIVER=${BOOKSTACK_MAIL_DRIVER}
      - MAIL_HOST=${BOOKSTACK_MAIL_HOST}
      - MAIL_PORT=${BOOKSTACK_MAIL_PORT}
      - MAIL_ENCRYPTION=${BOOKSTACK_MAIL_ENCRYPTION}
      - MAIL_USERNAME=${BOOKSTACK_MAIL_USERNAME}
      - MAIL_PASSWORD=${BOOKSTACK_MAIL_PASSWORD}
      - MAIL_FROM=${BOOKSTACK_MAIL_FROM}
      - MAIL_FROM_NAME=${BOOKSTACK_MAIL_FROM_NAME}
      - QUEUE_CONNECTION=${BOOKSTACK_QUEUE_CONNECTION}
    volumes:
      - /mnt/appdata/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped

    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
