version: '3.9'
services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker:dev-arm
    hostname: speedtest
    volumes:
      - /opt/appdata/speedtest:/config
    environment:
      - TZ=${SPEEDTEST_TZ}
      - PGID=${SPEEDTEST_PGID}
      - PUID=${SPEEDTEST_PUID}
      - OOKLA_EULA_GDPR=${SPEEDTEST_OOKLA_EULA_GDPR}
    ports:
      - 8765:80
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
