version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v4.10.2
    hostname: dozzle
    environment:
      - DOZZLE_USERNAME=admin
      - DOZZLE_PASSWORD=${DOZZLE_PASSWORD}
      - DOZZLE_KEY=${DOZZLE_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2123:8080
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true

