version: '3.9'

services:
  minio-shinpuru:
    image: 'minio/minio:latest'
    expose:
      - '9000'
    volumes:
      - '/mnt/appdata/shinpuru/minio/data:/data'
    environment:
      MINIO_ACCESS_KEY: 'minio_access_key'
      MINIO_SECRET_KEY: 'minio_secret_key'
      MINIO_REGION_NAME: 'us-east-1'
    command: server /data # --certs-dir /etc/cert
    restart: always
    networks:
      - proxy

  redis-shinpuru:
    image: 'redis:latest'
    expose:
      - '6379'
    restart: always
    networks:
      - proxy

  mysql-shinpuru:
    image: 'mariadb:latest'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${SP_DATABASE_MYSQL_PASSWORD}
      MYSQL_DATABASE: shinpuru
    volumes:
      - '/mnt/appdata/shinpuru/mysql/cfg:/etc/mysql'
      - '/mnt/appdata/shinpuru/mysql/lib:/var/lib/mysql'
    restart: always
    networks:
      - proxy

  shinpuru:
    image: 'ghcr.io/zekrotja/shinpuru:latest'
    volumes:
      - '/mnt/appdata/shinpuru/config:/etc/config'
      - '/mnt/appdata/shinpuru/cert:/etc/cert'
    expose:
      - '8080'
    environment:
      SP_VERSION: 6
      # Discord Config
      SP_DISCORD_TOKEN: ${SP_DISCORD_TOKEN}
      SP_DISCORD_GENERALPREFIX: sp!
      SP_DISCORD_OWNERID: ${SP_DISCORD_OWNERID}
      SP_DISCORD_CLIENTID: ${SP_DISCORD_CLIENTID}
      SP_DISCORD_CLIENTSECRET: ${SP_DISCORD_CLIENTSECRET}
      SP_DISCORD_GUILDSLIMIT: 0
      SP_DISCORD_GLOBALCOMMANDRATELIMIT_ENABLED: 1
      SP_DISCORD_GLOBALCOMMANDRATELIMIT_BURST: 3
      SP_DISCORD_GLOBALCOMMANDRATELIMIT_LIMITSECONDS: 20
      # Database
      SP_DATABASE_TYPE: mysql
      SP_DATABASE_MYSQL_HOST: mysql-shinpuru
      SP_DATABASE_MYSQL_USER: root
      SP_DATABASE_MYSQL_PASSWORD: ${SP_DATABASE_MYSQL_PASSWORD}
      SP_DATABASE_MYSQL_DATABASE: shinpuru
      # Cache
      SP_CACHE_REDIS_ADDR: redis-shinpuru:6379
      SP_CACHE_REDIS_TYPE: 0
      SP_CACHE_CACHEDATABASE: 1
      # Logging
      SP_LOGGING_COMMANDLOGGING: 1
      SP_LOGGING_LOGLEVEL: 4
      # Storage
      SP_STORAGE_TYPE: minio
      SP_STORAGE_MINIO_ENDPOINT: minio-shinpuru:9000
      SP_STORAGE_MINIO_ACCESSKEY: minio_access_key
      SP_STORAGE_MINIO_ACCESSSECRET: minio_secret_key
      SP_STORAGE_MINIO_LOCATION: us-east-1
      SP_STORAGE_MINIO_SECURE: 0
      # Webserver
      SP_WEBSERVER_ENABLED: 1
      SP_WEBSERVER_ADDR: 0.0.0.0:8080
      SP_WEBSERVER_APITOKENKEY: ${SP_WEBSERVER_APITOKENKEY}
      SP_WEBSERVER_PUBLICADDR: ${SP_WEBSERVER_PUBLICADDR}
      SP_WEBSERVER_RATELIMIT_ENABLED: 1
      SP_WEBSERVER_RATELIMIT_BURST: 50
      SP_WEBSERVER_RATELIMIT_LIMITSECONDS: 3
      SP_WEBSERVER_ACCESSTOKEN_LIFETIMESECONDS: 600
      SP_WEBSERVER_CAPTCHA_SITEKEY: ${SP_WEBSERVER_CAPTCHA_SITEKEY}
      SP_WEBSERVER_CAPTCHA_SECRETKEY: ${SP_WEBSERVER_CAPTCHA_SECRETKEY}
      # Codeexec
      SP_CODEEXEC_TYPE: "ranna"
      SP_CODEEXEC_RANNA_APIVERSION: "v1"
      SP_CODEEXEC_RANNA_ENDPOINT: "https://public.ranna.dev"
      SP_CODEEXEC_RATELIMIT_ENABLED: 1
      SP_CODEEXEC_RATELIMIT_BURST: 5
      SP_CODEEXEC_RATELIMIT_LIMITSECONDS: 60
      # Privacy
      # ⚠️ YOU MUST CHANGE THIS WHEN YOU HOST YOUR SHINPURU INSTANCE PUBLICLY!
      SP_PRIVACY_NOTICEURL: "https://github.com/zekroTJA/shinpuru/blob/master/PRIVACY.md"
      SP_PRIVACY_CONTACT_0_TITLE: "E-Mail"
      SP_PRIVACY_CONTACT_0_VALUE: "admin@domain.com"
      SP_PRIVACY_CONTACT_0_URL: "mailto:admin@domain.com"
    restart: always
    depends_on:
      - mysql-shinpuru
      - redis-shinpuru
      - minio-shinpuru
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true