version: '3.9'
services:
  mariadb:
    image: linuxserver/mariadb:10.11.6
    container_name: mariadb
    hostname: mariadb
    environment:
      - PUID=${MARIADB_PUID}
      - PGID=${MARIADB_PGID}
      - MYSQL_ROOT_PASSWORD=${MARIADB_MYSQL_ROOT_PASSWORD}
      - TZ=${MARIADB_TZ}
      - MYSQL_DATABASE=${MARIADB_MYSQL_DATABASE}
      - MYSQL_USER=${MARIADB_MYSQL_USER}
      - MYSQL_PASSWORD=${MARIADB_MYSQL_PASSWORD}
    volumes:
      - /mnt/appdata/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
