version: '3'
services:
  dupeguru:
    container_name: dupeguru
    image: jlesage/dupeguru:v23.06.1
    hostname: dupeguru
    environment:
      - TZ=${DUPEGURU_TZ}
      - DISPLAY_WIDTH=${DUPEGURU_DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DUPEGURU_DISPLAY_HEIGHT}
      - SECURE_CONNECTION=${DUPEGURU_SECURE_CONNECTION}
      - ENABLE_CJK_FONT=${DUPEGURU_ENABLE_CJK_FONT}
      - UMASK=${DUPEGURU_UMASK}
    ports:
      - 57801:5800
      - 7901:5900
    volumes:
      - /mnt/appdata/dupeguru:/config:rw
      - /mnt/appdata/dupeguru/storage:/storage:rw
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
