name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

     - name: Tag Creation
        id: semantic_release
        run: |
          output=$(npx semantic-release 2>&1)
          echo "$output"
          tag=$(echo "$output" | grep 'Created tag' | sed -E 's/.*Created tag ([^ ]+).*/\1/')
          echo "::set-output name=tag::$tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semantic_release.outputs.tag }}
          name: ${{ steps.semantic_release.outputs.tag }}
          body: ${{ steps.git-cliff.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}