name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Create Release Branch
        run: |
          git checkout -b release-${GITHUB_RUN_ID}
          git push origin release-${GITHUB_RUN_ID}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          npx semantic-release --branches release-${GITHUB_RUN_ID}

      - name: Open Pull Request
      - uses: actions/checkout@v4
        run: |
          PR_URL=$(gh pr create --base main --head release-${GITHUB_RUN_ID} --title "Release PR for version update" --body "This PR is auto-generated by GitHub Actions to update the package version." --assignee NorkzYT --repo ${{ github.repository }} 2>&1)
          echo "$PR_URL" || echo "PR may already exist or another error occurred."
