version: '3.9'
services:
  pterodactyl-panel:
    image: ccarney16/pterodactyl-panel:v1.11.5
    container_name: pterodactyl-panel
    hostname: pterodactyl-panel
    ports:
      - 8025:80
    # chmod -R 600 /mnt/appdata/pterodactyl/panel/game.data/config.yml -- IF Panel changes configuration and breaks the node.
    volumes:
      - /mnt/appdata/pterodactyl-panel/appdata/:/data #Appdata
      - /mnt/appdata/pterodactyl-wings:/etc/pterodactyl #Where config.yml goes into. #Appdata
      - /mnt/appdata/pterodactyl-wings/data:/mnt/appdata/pterodactyl-wings/data #Shared data between Panel and Wings.
      - /mnt/appdata/pterodactyl-panel/nginx/:/etc/nginx/conf.d/ #Nginx Config
    environment:
      - APP_ENV=${PTERODACTYL_PANEL_APP_ENV}
      - APP_ENVIRONMENT_ONLY=${PTERODACTYL_PANEL_APP_ENVIRONMENT_ONLY}
      - APP_SERVICE_AUTHOR=${PTERODACTYL_PANEL_APP_SERVICE_AUTHOR}
      - APP_URL=${PTERODACTYL_PANEL_APP_URL}
      - APP_TIMEZONE=${PTERODACTYL_PANEL_APP_TIMEZONE}
      - CACHE_DRIVER=${PTERODACTYL_PANEL_CACHE_DRIVER}
      - SESSION_DRIVER=${PTERODACTYL_PANEL_SESSION_DRIVER}
      - QUEUE_DRIVER=${PTERODACTYL_PANEL_QUEUE_DRIVER}
      - REDIS_HOST=${PTERODACTYL_PANEL_REDIS_HOST}
      - REDIS_PORT=${PTERODACTYL_PANEL_REDIS_PORT}
      - REDIS_USER=${PTERODACTYL_PANEL_REDIS_USER}
      - REDIS_PASSWORD=${PTERODACTYL_PANEL_REDIS_PASSWORD}
      - MAIL_FROM=${PTERODACTYL_PANEL_MAIL_FROM}
      - MAIL_DRIVER=${PTERODACTYL_PANEL_MAIL_DRIVER}
      - MAIL_HOST=${PTERODACTYL_PANEL_MAIL_HOST}
      - MAIL_PORT=${PTERODACTYL_PANEL_MAIL_PORT}
      - MAIL_USERNAME=${PTERODACTYL_PANEL_MAIL_USERNAME}
      - MAIL_PASSWORD=${PTERODACTYL_PANEL_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${PTERODACTYL_PANEL_MAIL_ENCRYPTION}
      - APP_DEBUG=${PTERODACTYL_PANEL_APP_DEBUG}
      - TRUSTED_PROXIES=${PTERODACTYL_PANEL_TRUSTED_PROXIES}
      - DB_HOST=${PTERODACTYL_PANEL_DB_HOST}
      - DB_PORT=${PTERODACTYL_PANEL_DB_PORT}
      - DB_USER=${PTERODACTYL_PANEL_DB_USER}
      - DB_PASSWORD=${PTERODACTYL_PANEL_DB_PASSWORD}
      - DB_DATABASE=${PTERODACTYL_PANEL_DB_DATABASE}
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
