version: '3.9'
services:

  node-red:
    image: nodered/node-red:2.2.3-12
    container_name: node-red
    hostname: node-red
    environment:
      - TZ=${NODE_RED_TZ}
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - /mnt/appdata/node-red/data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true



# Run the following command to be able to give `node-red` file permission so it can work.
# sudo chmod -R 775 /mnt/appdata/node-red   #(VOLUME FOLDER)

