# Installation: https://nodered.org/docs/getting-started/docker

services:
  node-red:
    image: nodered/node-red:2.2.3-12
    container_name: node-red
    environment:
      - TZ=${NODE_RED_TZ}
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - /opt/appdata/node-red:/data
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
