version: '3.9'
services:
  endlessh:
    image: linuxserver/endlessh:version-dfe44eb2
    container_name: endlessh
    environment:
      - PUID=${ENDLESSH_PUID}
      - PGID=${ENDLESSH_PGID}
      - TZ=${ENDLESSH_TZ}
      - MSDELAY=${ENDLESSH_MSDELAY}
      - MAXLINES=${ENDLESSH_MAXLINES}
      - MAXCLIENTS=${ENDLESSH_MAXCLIENTS}
      - LOGFILE=${ENDLESSH_LOGFILE}
      # - BINDFAMILY=${ENDLESSH_BINDFAMILY}
    volumes:
      - /mnt/appdata/endlessh:/config #optional
    ports:
      - 2222:2222
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
